# a docker-compose.yml to start a simple cluster with three ZooKeeper nodes and three Solr nodes.
# Sourced from https://github.com/docker-solr/docker-solr-examples

version: '3.7'
services:

  tika1:
    container_name: tika1
    build: ./tika-to-the-max
    ports:
     - "9998:9998"
    networks:
      - solr
    depends_on:
      - spacy

  spacy:
    container_name: spacy
    image: jgontrum/spacyapi:en_v2
    ports:
     - "8080:80"
    networks:
      - solr

  solr1:
    container_name: solr1
    build: ./solr
    ports:
     - "8983:8983"
    environment:
      - SOLR_OPTS=-XX:-UseLargePages
      - SOLR_HEAP=800m
      - ZK_HOST=zoo1:2181,zoo2:2181,zoo3:2181
    volumes:
      - ./volumes/fake_shared_fs:/tmp/fake_shared_fs
    depends_on:
      - zoo1
      - zoo2
      - zoo3

  solr2:
    container_name: solr2
    build: ./solr
    ports:
     - "8984:8983"
    environment:
      - SOLR_OPTS=-XX:-UseLargePages
      - SOLR_HEAP=800m
      - ZK_HOST=zoo1:2181,zoo2:2181,zoo3:2181
    volumes:
      - ./volumes/fake_shared_fs:/tmp/fake_shared_fs
    depends_on:
      - zoo1
      - zoo2
      - zoo3

  solr3:
    container_name: solr3
    build: ./solr
    ports:
     - "8985:8983"
    environment:
      - SOLR_OPTS=-XX:-UseLargePages
      - SOLR_HEAP=800m
      - ZK_HOST=zoo1:2181,zoo2:2181,zoo3:2181
    volumes:
      - ./volumes/fake_shared_fs:/tmp/fake_shared_fs
    depends_on:
      - zoo1
      - zoo2
      - zoo3

  zoo1:
    image: zookeeper:3.6.2
    container_name: zoo1
    hostname: zoo1
    ports:
      - 2181:2181
      - 7000:7000
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
      ZOO_4LW_COMMANDS_WHITELIST: mntr, conf, ruok
      ZOO_CFG_EXTRA: "metricsProvider.className=org.apache.zookeeper.metrics.prometheus.PrometheusMetricsProvider metricsProvider.httpPort=7000 metricsProvider.exportJvmInfo=true"


  zoo2:
    image: zookeeper:3.6.2
    container_name: zoo2
    hostname: zoo2
    ports:
      - 2182:2181
      - 7001:7000
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
      ZOO_4LW_COMMANDS_WHITELIST: mntr, conf, ruok
      ZOO_CFG_EXTRA: "metricsProvider.className=org.apache.zookeeper.metrics.prometheus.PrometheusMetricsProvider metricsProvider.httpPort=7000 metricsProvider.exportJvmInfo=true"


  zoo3:
    image: zookeeper:3.6.2
    container_name: zoo3
    hostname: zoo3
    ports:
      - 2183:2181
      - 7002:7000
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
      ZOO_4LW_COMMANDS_WHITELIST: mntr,conf,ruok
      ZOO_CFG_EXTRA: "metricsProvider.className=org.apache.zookeeper.metrics.prometheus.PrometheusMetricsProvider metricsProvider.httpPort=7000 metricsProvider.exportJvmInfo=true"
